name: test tag

on:
  release:
    types: [published]
    
jobs:
  details:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract tag name
        id: release
        run: |
          echo "Ran after release"
